image: python:3.6-slim-stretch
lint:
  script:
    - pip3 install black flake8
    - export EXITVALUE=0
    - black --check . || export EXITVALUE=1
    - flake8 || export EXITVALUE=1
    - exit $EXITVALUE

test:
  script:
    - pip3 install -r requirements.txt -r requirements-dev.txt
    - python3 -m pytest
