openapi: '3.0.2'
info:
  title: Pushserver API
  version: "0.1"
  description: HTTP API for the open pushserver implementation.

security:
  - basic_auth: []

paths:
  /user:
    get:
      tags:
        - user
      summary: Return all users.
      responses:
        '200':
          description: A list of all users.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Users"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags: 
        - user
      summary: Add a user.
      requestBody:
        description: the user to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          
  /user/{id}:
    get:
      tags: 
        - user
      summary: Get a user.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Ok.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: api.user.update
      tags: 
        - user
      summary: Update a user.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to update
          schema:
            type: string
      requestBody:
        description: Updated user details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          
      responses:
        '200':
          description: Created.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - user
      summary: Delete a user.
      parameters: 
        - name: id
          in: path
          required: true
          description: The id of the user to delete.
          schema:
            type: string
      responses:
        '204':
          description: Ok.
  
  /client:
    get:
      tags: 
        - client
      summary: Return all clients.
      responses:
        '200':
          description: A list of all clients for the current user.
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      operationId: api.client.delete_self
      tags:
        - client
      summary: Delete current client.
      security:
        - client_key: []
      responses:
        '200':
          description: Ok.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - client
      summary: Create a new client.
      requestBody:
        description: Client to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientRegistration"
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /client/{id}:
    put:
      tags:
        - client
      summary: Update a client.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the client to update
          schema:
            type: string
      requestBody:
        description: Updated client details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
          
      responses:
        '200':
          description: Ok.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Client"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - client
      summary: Delete a client.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the client to delete
          schema:
            type: string
      responses:
        '200':
          description: Ok.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /application:
    get:
      security:
        - client_key: []
      tags:
        - application
      summary: Get a list of all registered applications.
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Application"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      security:
        - client_key: []
      tags:
        - application
      summary: Register a new application.
      requestBody:
        description: Application to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Application"
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /application/{id}:
    delete:
      security:
        - client_key: []
      tags:
        - application
      summary: Delete an application.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the app to delete.
          schema:
            type: string
      responses:
        '204':
          description: Deleted.
      
    
  /message:
    post:
      security:
        - routing_token: []
      summary: Post a message.
      tags: [message]
      requestBody:
        description: Message to post.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        '200':
          description: Message posted.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /subscribe:
    get:
      operationId: api.message.subscribe
      security:
        - client_key: []
      summary: Subscribe to messages delivered via SSE (Server Sent Events) here
      tags: [message]
      responses:
        '200':
          description: Subscribed.
          content:
            text/event-stream: {}
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      
  
components:
  securitySchemes:
    client_key:
      type: apiKey
      name: X-Openpush-Key
      in: header
      x-apikeyInfoFunc: auth.clientkey_auth
    routing_token:
      type: apiKey
      name: X-Openpush-Key
      in: header
      x-apikeyInfoFunc: auth.routing_token_auth
    basic_auth:
      type: http
      scheme: basic
      x-basicInfoFunc: auth.basic_auth
  schemas:
    User:
      required:
        - id
        - name
        - password
        - clients
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
          example: 783
        name:
          type: string
          example: "User1"
        password:
          writeOnly: true
          format: string
          example: "SuperPassword123"
        clients:
          readOnly: true
          type: array
          items:
            $ref: "#/components/schemas/Client"

    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
        
    Application:
      description: A registered application installed on a client
      required: 
        - id
        - name
        - routing_token
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
        name:
          example: "riot-android"
          type: string
        routing_token:
          readOnly: true
          description: Token to target a mobile application.
          example: "8904j76gkjlsfdhalSKL"
          type: string

    ClientRegistration:
      description: Data for registering a new client
      required:
        - name
      properties:
        name:
          example: "Phone 1"
          type: string

    Client:
      description: A mobile client
      required:
        - id
        - name
        - applications
        - token
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
        name:
          example: "Phone 1"
          type: string
        token:
          example: "WDKZMxUFpdjlgiFVSx2A2rP5GSM"
          type: string
          readOnly: true
        applications:
          readOnly: true
          type: array
          items:
            $ref: "#/components/schemas/Application"

    Pushtoken:
      description: Token to target a mobile application.
      example: "8904j76gkjlsfdhalSKL"
      type: string
      
    Message:
      required: 
        - body
      properties:
        subject:
          example: "Message Subject"
          type: string
        body:
          example: "Long message text goes here..."
          type: string
        priority:
          type: string
          enum: [NORMAL, HIGH]
          
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
